image:
  tag: 6.2.7-debian-10-r22
  registry: reg.dev.krd
  repository: hub.docker/bitnami/redis

architecture: replication

sentinel:
  image:
    tag: 6.2.7-debian-10-r22
    registry: reg.dev.krd
    repository: hub.docker/bitnami/redis
  masterSet: mymaster
  enabled: true
  persistence:
    enabled: true
    storageClass: local-path
    size: 100Mi

master:
  persistence:
    size: 4Gi

replica:
  replicaCount: 1
  persistence:
    size: 4Gi

auth:
  sentinel: true
  enabled: true
